name: Generic Artifact Upload into Artifactory
description: Upload a generic artifact into Artifactory
author: DA Team <da.team@sherwin.com>

inputs:
  artifact_name:
    required: true
    description: 'Name of the artifact to be scanned'
  
  artifactory_secret:
    required: true
    description: 'JF Artifactory Token'
  
  artifact_path: 
    required: false
    default: '${{ github.workspace }}'
    description: 'Path to the artifact that needs to be scanned'

  artifactory_repo_name:
    required: false
    default: third-party-installs
    description: 'Location for artifact to be deployed to'
  
  artifactory_repo_subpath:
    required: false
    default: ${{ github.repository }}/${{ github.run_number }}
    description: 'Sub path under third-party-installs repo'
  
runs:
  using: "composite"
  steps: 
  - uses: jfrog/setup-jfrog-cli@v1
    env:
      JF_ARTIFACTORY_1: ${{ inputs.artifactory_secret }}
  
  - name: JFrog CLI Upload Artifact
    run: |
      jfrog rt upload --flat=false "${{ inputs.artifact_path }}/${{ inputs.artifact_name }}" ${{ inputs.artifactory_repo_name }}/${{ inputs.artifactory_repo_subpath }}/${{ inputs.artifact_name }}
    shell: bash
        
branding:
  icon: git-branch
  color: white
