# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: pull_request

jobs:
  test:
    runs-on: sw-ubuntu-latest
    steps:
    - run: 'Hello'
